combine_control_expr = false
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"

# max_width = 120
# attr_fn_like_width = 60
# chain_width = 60
# fn_call_width = 60

struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true
